services:
  expenses-ui:
    container_name: expenses-ui
    image: ghcr.io/smukherj1/expenses/expenses-ui:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - expenses-frontend

networks:
  expenses-frontend:
    driver: bridge