services:
  expenses-ui:
    container_name: expenses-ui
    image: ghcr.io/smukherj1/expenses/expenses-ui:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - expenses-frontend
    environment:
      TRANSACTIONS_SERVER_ENDPOINT: http://expenses-server:4000/v1/transactions
  expenses-server:
    hostname: expenses-server
    container_name: expenses-server
    image: ghcr.io/smukherj1/expenses/expenses-server:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - expenses-frontend
      - expenses-backend
    environment:
      SPRING_PROFILES_ACTIVE: test
  expenses-db:
    hostname: expenses-db
    image: postgres:18.0-alpine3.22
    restart: unless-stopped
    container_name: expenses-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - expenses-db_data:/var/lib/postgresql/data
    networks:
      - expenses-backend

volumes:
  expenses-db_data:

networks:
  expenses-frontend:
    driver: bridge
  expenses-backend:
    driver: bridge
